name: excellence_digital_app
description: Excellence Digital Center - Application Mobile
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.16
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  lottie: ^3.3.1
  flutter_animate: ^4.5.2
  
  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  
  # Network
  dio: ^5.7.0
  connectivity_plus: ^6.1.1
  
  # Storage
  shared_preferences: ^2.3.4
  flutter_secure_storage: ^9.2.4
  
  # Utils
  intl: ^0.19.0
  url_launcher: ^6.3.1
  file_picker: ^8.1.7
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  
  # PDF Viewer (gratuit)
  flutter_pdfview: ^1.3.4
  
  # Paiement
  flutter_stripe: ^11.3.0
  
  # Notifications
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1
  
  # WebView
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.6.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/